### ISSUE TITLE
Sidebar displays color gradient on the left side of folder icons

### ISSUE THREAD

**Issue by xuansamdinh** [saadq/Materialize#34]
Materialize has been auto updated to version 2.5.1 via Package Control. Then I've got this issues, as pictured bellow.

- Sublime Text: build 3083.
- Materialize: 2.5.1.

![materialize_2 5 1_folder](https://cloud.githubusercontent.com/assets/950027/12371184/dc2c069a-bc5d-11e5-8eb7-0641e9a0afe4.png)

**Comment by saadq** [comment]
Did you try restarting the editor? Let me know if that still doesn
t fix it.

**Comment by saadq** [comment]
The last change I did messed up the color of the sidebar in contrast mode, but the graphic corruption shouldn't be there. Restarting should fix it. I just sent a patch that will fix the sidebar color again, your theme should update again shortly.

**Comment by xuansamdinh** [comment]
Thanks for reply!

I've restarted the editor at least a couple of times, but the problem is still there. I'm waiting for the update.
./.

**Comment by saadq** [comment]
The update will most like only change the color of the sidebar. I would recommend trying to uninstall the Materialize package and then reinstalling it.

**Comment by xuansamdinh** [comment]
Remove and then re-install the Materialize package fix the problem.

Procedure:
=========
- Remove the Material package.
- Restart the editor.
- Install the Material. No editor restart requirement.

Thank you!

Should I close this issue now?

**Comment by saadq** [comment]
Glad it worked!
